#!/bin/bash
export GOPATH=`pwd`
git pull
pushd src && rm -rf github.com/cybergarage/go-graphite.git github.com/cybergarage/go-graphite && popd
go get -u github.com/cybergarage/go-graphite.git/net/graphite
pushd src && mv github.com/cybergarage/go-graphite.git github.com/cybergarage/go-graphite && popd
